var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/forgot-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0006a32e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f0343b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_db14db6f._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__24c95238._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__b500bd8e._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.c("server/chunks/ssr/_f920469a._.js")
R.m(93137)
R.m(20880)
module.exports=R.m(20880).exports
